### ISSUE TITLE
Testing demo notebooks and pytest

### ISSUE THREAD

**Issue by jooh** [rsagroup/rsatoolbox#142]
It would be useful to include the demo notebooks in tests to detect any regressions. I did some research and there seems to be two ways you could do this.

1. Add dependencies: pytest and [nbval](https://nbval.readthedocs.io/en/latest/). This is the most elegant approach. See e.g. [this example application](https://github.com/miykael/workshop_cambridge/blob/master/test_notebooks.py). But we would be switching the test backend to pytest (which is compatible with the existing unittest tests, but all the same, it will at a minimum require messing with CI). For what it's worth, I think pytest is much nicer than unittest anyway.

2. You can hack together your own unittest notebook runner by running something like `jupyter nbconvert --to notebook --inplace --execute mynotebook.ipynb` in a subprocess, and re-throwing any exceptions that come back from the shell. I got this idea from [this SO answer](https://stackoverflow.com/a/40311709/3375155). No further dependencies, but I have a feeling this may or may not work well in practice, since you're calling a nested python process and that introduces fun possibilities like somehow picking up a *different* python from the original test runner...

Any thoughts on this?

**Comment by JasperVanDenBosch** [comment]
I think this is a good idea as long as it doesn't lead to people being lax about unit testing.

Both solutions would be fine with me as long as we have a convention for which framework to write the tests in. Personally I think I'd prefer to keep writing them as standard library tests, so if `pytest` supports these that would work.

I don't use the notebooks myself so I don't have a deep knowledge about the custom kernels and how they work (and how 1. or 2. could be unreliable or not).

**Comment by HeikoSchuett** [comment]
So first: I think pytest should work well for all the tests we currently have. In fact I usually use pytest to run the tests locally and this works fine. 

At the same time I am not really convinced that running the tutorial notebooks directly is the way to go to check that the workflows still work right. Notebooks are quite annoying for testing because they contain all the information about when what code was run, the graphical outputs etc., as reflected in the relatively long list of necessary adjustments on the front-page of the Nbval package. 
Also the tutorial notebooks are not great tests, because they contain random parts, sometimes quite lengthy computations, many irrelevant illustrations, and other issues.
So maybe the best we could do for the notebooks themselves is check that they still run? For all notebooks, this now already takes quarter an hour or so I think which is not ideal for testing during development, but could be done once before merging.

For testing that the actual results stay the same it may be easier to add a couple of lengthier tests, which are not unit tests, but tests which check that the results for these workflows stay the same. These could be generated as a condensed version of some demo notebooks, but would avoid the long computations and all the things which would have to be removed from the test evaluation of the notebooks. 

The main thing I would like to avoid is placing stronger burdens on people for writing the tutorial notebooks.

**Comment by jooh** [comment]
> So maybe the best we could do for the notebooks themselves is check that they still run? 

Yes, this is all I had in mind! Not formal testing of the accuracy of each cell, just checking that all the cells run without returning exceptions.

Also agree that the time it takes to run the notebooks makes it overkill for the standard test suite. Maybe best to have a separate test_notebooks.py under `demos/` that can be run before releases?

**Comment by HeikoSchuett** [comment]
I just sat down and wrote a couple of tests based on the existing notebooks. That did not take much time and should now test whether the code they want to run still works. 

On your last point: I agree that we should probably test the notebooks before releases. I don't really know a way which makes this much easier than clicking through them once. If you do, please feel free to add such a test script!
