### ISSUE TITLE
Errors in the "exercise_all" DEMO

### ISSUE THREAD

**Issue by Jiashun97** [rsagroup/rsatoolbox#157]
![Screen Shot 2020-10-20 at 14 47 11](https://user-images.githubusercontent.com/65221219/96587838-23a7ae80-12e3-11eb-9697-9bf1e22e1583.png)

I upgraded to a new version but the error in #156 is still there.

**Comment by Jiashun97** [comment]
I solved the problem by adding "pattern_descriptor = 'index' " in the arguments of the function pyrsa.inference.sets_k_fold

**Comment by HeikoSchuett** [comment]
This is a bit odd. The fix you used is exactly what should happen in the current version anyway. I am glad you found the solution, but this is the default in the current master branch:
```
    def sets_k_fold(rdms, k_rdm=5, k_pattern=5, random=True,
                    pattern_descriptor='index', rdm_descriptor='index'):
```
(copy pasted from the code)

Maybe check whether the version you have loaded in the notebook is indeed updated. 

Otherwise: Have fun with the toolbox

**Comment by Jiashun97** [comment]
Yeah I tried again and I got the same error after re-installation. There might be sth wrong with the way I import it. If other people can use it then I think this is fine. Thank you.
