### ISSUE TITLE
Fallback option for Noise Estimate

### ISSUE THREAD

**Issue by smazurchuk** [rsagroup/rsatoolbox#214]
In a current experiment we have 300 conditions each of which is sampled 6 times (so 1800 bmaps). A reasonable size ROI (default mode network in left-hemisphere) has about 7,000 vertices in the hcp mesh. At present, it seems this is too large of an ROI for the toolbox to handle calculating the crossnobis distance of. Are there any pointers for using datasets of this size?

This can be recreated with the following code:
```python
import numpy as np
import rsatoolbox as rsa

# Load dataset
dset = np.random.rand(1800,7000)

# Generate Word and presentation numbers
words = []; 
for i in range(1800):
    words.append(f'_{int(i/6)}_')

# Calculate Distance
tmp    = dset
tmp_ds = rsa.data.dataset.Dataset(measurements = tmp,
         descriptors = {'subj':1},
         obs_descriptors = {'words':words})
ds_noise = rsa.data.noise.prec_from_measurements(tmp_ds, obs_desc='words', method='diag')
```
gives
```pre
MemoryError: Unable to allocate 657. GiB for an array with shape (1800, 7000, 7000) and data type float64
```

![image](https://user-images.githubusercontent.com/29523859/143144751-233db754-4af5-4740-ae91-536488b32b5b.png)

**Comment by iancharest** [comment]
Hi Stephen,

I can see two memory improvements.

First, declare your data .astype(np.float32)

That should cut size in half.

Second, and this is more internal to rsatoolbox, as far as I understand,
there is no need to store Square rdms at any point. Only storing the upper
triangular vectors should reduce memory use even more.

I'll look into it by the end of the week.

ian

**Comment by smazurchuk** [comment]
Hey @iancharest , thanks!

I can switch to float32, but for this case, I still would be out of memory. I guess I have some theory questions. It seems to me that estimating the covariance/noise matrix is needed to make `crossnobis` scale invariant. Are there any other ways to do this? 

As a work-around, can we just scale activation patterns to unit length? Then if we use the cross-validated mahalanobis distance with the identity noise matrix (giving us a cross-validated euclidean distance), would we effectively get a cross-validated cosine distance? This would then be scale invariant. Taking this a step further, if we mean center each pattern **and** make it unit length, would we in effect have a cross-validated correlation distance?

Intuitively, euclidean distance is related to cosine distance

![image](https://user-images.githubusercontent.com/29523859/143275744-8f34c978-29f9-4d3d-b4cb-1932036fc1f2.png)

If you normalize each pattern

![image](https://user-images.githubusercontent.com/29523859/143275805-f2d51ce6-e5ec-41ab-ba73-90d8438a99eb.png)

![image](https://user-images.githubusercontent.com/29523859/143275842-f8cc27b9-4c2c-41a8-bb80-4568cf2ae340.png)

**Comment by HeikoSchuett** [comment]
Hi @smazurchuk, 

I think this is a bit more internal. The memory problem happens in the noise covariance estimation, not in the actual calculation of the RDM. The big array appears in the calculation of the shrinkage estimate, where we also need some information across the time dimension. If the data fit in memory it is simplest and fastest to just keep the inner products of residuals for all timepoints, but this can be accumulated, too, to save memory.

On your ideas of other normalizations: I would still think of this as a covariance or precision matrix. The noise covariance is less for normalizing the patterns, but for using the right weighting between voxels. Voxels that are noisy or highly correlated should be weighted less than independent, precise voxels.
If you want to avoid the use of a full covariance matrix, you can instead use only a diagonal of variances per channel, which implements univariate noise normalization. You should be able to pass that as a vector. 
Or if you don't want to take the noise covariance into account at all, you can leave the noise precision unset and use the identity matrix implicitly.

You can define cross-validated versions of the cosine dissimilarity and correlation distance. These are not directly related to discriminability of the patterns though and removing information from the original patterns is typically not advantageous. That's why we usually stick with the euclidean/mahalanobis squared distance.

**Comment by smazurchuk** [comment]
Hi @HeikoSchuett , thanks for the reply!

> The memory problem happens in the noise covariance estimation, not in the actual calculation of the RDM

Yep, that's why I didn't include that step in the example code (and raised it as an issue, as there might be people interested in using ROI's that have  a few thousand voxels). Perhaps this is just impractical though. 

> Or if you don't want to take the noise covariance into account at all, you can leave the noise precision unset and use the identity matrix implicitly

This is what I do for speed, but the issue is that since the patterns are not scale invariant, you can't average RDM's across subjects in a large ROI. When you use correlation/cosine distance, I think you **can** average RDM's together because each one is scale invariant. I think taking into account the covariance structure is ideal, even if just univariate noise normalization, but would that make the resulting RDM scale invariant? 

Do you have any thoughts for how I should average RDM's from `crossnobis` distance with either identity or diagonal of variances per channel? Would normalizing each image be sufficient to justify averaging RDM's?

**Comment by jdiedrichsen** [comment]
@smazurchuk :  The most practical approach to achieving some scale-constancy on you distances for large ROIs is to use uni-variate prewhitening (i.e. divide the beta values of each voxel / vertex by the SD of the first-level GLM), rather than using multivariate -prewhitening, which demands the estimation of a voxel x voxel covariance matrix.  As shown in Walther et al. (2016) univariate prewhitening already gives you the main improvement. AS a result subjects with a larger signal-to-noise level will have larger distances and influence the group mean more, which maybe what you want.

**Comment by HeikoSchuett** [comment]
That pooling question is largely separate, I think.

Essentially, how you pool RDMs from different subjects comes in a pair with how you compare RDMs to each other. Thus I view this as a part of the second step of RSA of computing with RDMs. Almost all comparison metrics remove the scale of the RDM per subject anyway by normalizing away the scale of the RDM. That would be a standard place to remove it.

There is a function `rsatoolbox.util.pooling.pool_rdm` that computes this type of averaging for all implemented RDM comparison metrics.

If you truly want an interpretable scale in a case like what @jdiedrichsen describes, it would depend on what you think should be comparable. What Jörn describes would weigh differences relative to the noise. Other methods could normalize them to some specific response strength or almost anything else you think gives you a comparable measure across subjects.

**Comment by smazurchuk** [comment]
Hi @jdiedrichsen ! Thanks for the reply, and sorry for asking so many questions on this thread! I reference that paper quite often (so thanks!). We use that paper to justify doing RSA with the t-statistics that come from afni's [`3dREMLfit`](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dREMLfit.html) which uses an ARMA(1,1) model. It's a stretch but I was trying to do univariate pre-whitening and get an unbiased distance measure. I'm not sure this will be easy with something like afni as the t-value comes from all 6 presentations where each condition is its own regressor (and with an AR noise model), whereas individual trial beta-maps come from 1 vs all other design matrix [`3dLSS`](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dLSS.html)

@HeikoSchuett Thanks for all the feedback and help on these issues. Removing it at the RDM level makes sense. I guess I wasn't thinking of that because I normally just directly average RDM's that come from correlation distance so I was thinking of solutions from that perspective. 

Thanks everyone. I can close this unless people are interesting in changing the behavior of `rsa.data.noise.prec_from_measurements` for large ROI's
