### ISSUE TITLE
Appropriate method to test vs 0

### ISSUE THREAD

**Issue by smazurchuk** [rsagroup/rsatoolbox#222]
Hi all. This is kinda a basic use question, not so much an issue. I'm not sure if there is a better discussion forum, so if there is I can close this and ask the question there. 

My question is about the best way to test if a given patch contains linearly decodable information about different conditions. Conceptually, this seems to amount to a noise ceiling, but I was wondering how this relates to this arxiv paper

https://arxiv.org/abs/1607.01371

For a concrete example, a dataset we have has 50 conditions across 20 subjects. It seems clear that we **cannot** simply do a t-test against zero on the average crossnobis derived RDM. However, the above paper says that we **can** use a z-score derived from a multivariate normal approximation. 

![image](https://user-images.githubusercontent.com/29523859/146101401-4f7f6e03-d7be-4964-91d6-c6d03c44b4d9.png)

My question is whether estimating **V** (using `rsatoolbox.data.noise.cov_from_measurements`) and then calculating the z-score of the average(RDM) is conceptually the same as using the function `rsatoolbox.inference.noise_ceiling.boot_noise_ceiling` and looking at the p-value of the upper nc-bound?

The approaches feel very different to me, so I was wondering if one was more kosher than the other. 

Thanks in advance

**Comment by JasperVanDenBosch** [comment]
hi Stephen, I'm definitely ok with this category of questions here. I've edited the title to make it easier for people browsing the issues.

**Comment by smazurchuk** [comment]
Hi all. Maybe I could phrase the question differently. At present the lower noise ceiling is computed as one subjects RDM correlation with the average of the remaining subjects RDMs. This measures something like **shared variance across individuals**. However, it could also be useful to define something akin to a "within subject" noise ceiling. This would be something like where there is reliable information across presentations.

Intuitively, a within subject noise ceiling could be how RDMs derived from one presentation correlate with an RDM derived from all remaining presentations. It seems to me that with cross-validated distance measures, we already have a measure of this. What I am not sure whether we can simply take the mean crossnobis value of an RDM as a measure of the within subject noise ceiling? It seems from the above paper that we cannot because the mean value is inflated due to the covariance structure implicit in the RDM

**Comment by HeikoSchuett** [comment]
As the lack of quicker responses might suggest this is not a simple question. I will try to give some answer, but I don't think it is entirely solved. 

First, the two kinds of tests you describe are indeed different. All noise ceilings and their bootstrap distributions are computed based on generalization across the subjects and with a single subject we don't have anything to base our estimates of this generalization on. In contrast, the other tests and the distribution for RDMs is based on the measurement noise and thus about inferring back the RDM for the one particular subject. Thus, the noise ceilings being above a null-model tests for some generalizable structure, while the distribution would test whether the observed RDM could be expected from pure noise. 

Now, in principle using the distribution derived from the paper you cite could be used to test against 0. However, there are at least two caveats to this, one technical, one more about the interpretation: 

- The technical problem is, that the computation of the covariance requires the covariances across channels and across patterns, which both are quite uncertain given typical amounts of data. Thus, even if the covariance estimates are on average correct, a correction similar to the step from normal distributions to t-distributions due to the uncertainty about the covariance seems necessary and I at least don't immediately know how to do that correctly. Especially, if shrinkage estimates or regularization are used to estimate these covariances.
- On an interpretation level: Keep in mind that testing for any replicable pattern of responses within a single subject is a really low bar to cross. Thus, testing for that bar is almost meaningless. You may often find this to be significant without any discernible pattern visible in the RDM and even if you find one, this test would not allow you to interpret that pattern. To show that any particular pattern exists you would have to test a model that implements the hypothesis against 0.

If you still want to test for any discriminability, Hamed Nili et al. discuss a range of different tests for testing for pattern discriminability in this recent paper:
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0232551

BTW: Most of the content of the preprint you cite is now also properly published here:
https://nbdt.scholasticahq.com/article/27664-comparing-representational-geometries-using-whitened-unbiased-distance-matrix-similarity

**Comment by nkriegeskorte** [comment]
dear stephen, 

your original question "about the best way to test if a given patch contains linearly decodable information about different conditions." is addressed in nili et al. 2020 (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0232551; unfortunately you'll also need to download this correction to see the figure legends https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0250474). 

if your H0 is that none of the pairs of conditions (or none within some subset of pairs of conditions) is at all decodable, and you are just looking to reject that, then you can compute the average of the crossnobis estimates (or the LD-t values) for all relevant pairs of conditions within each subject. you can then do a t test against 0, using the across-subject variance of these single-subject means.

the effect size here cannot provide a noise ceiling for RSA. to see this, consider the fact that if the RDM were flat (all values the same), there could be much decoding information, but no significant RDM correlation among subjects or between a subject and a model. conversely, however, if you show significant RDM correlation among subjects or between a subject and any model (e.g. using the condition-label randomization test), then this does indicate that there is some information about the conditions in the response patterns.

as heiko said, this is a low bar. but it's sometimes important to demonstrate the presence of linearly decodable information.

niko

**Comment by JasperVanDenBosch** [comment]
As there is no further questions, I'm considering this was resolved and closing it
