### ISSUE TITLE
Indicator module only handles row vectors

### ISSUE THREAD

**Issue by saarbuckle** [rsagroup/rsatoolbox#23]
My understanding is that the `index_vector` passed to any function in `indicator.py` is a column vector (of same size as the number of rows in `data.measurements`), but it seems the indicator functions only work with row vectors. 
Given my limited python experience, I don't see a fully satisfactory fix to allow dynamic handling of row or column vectors. Any insights? Or should we always assume a specific dimensionality?

**Comment by saarbuckle** [comment]
I should be more clear about why I've raised this issue. This is easily fixed, but the question is whether this fix should be a dimension check (which would have to be applied for each function call, which sounds cumbersome), or should it be a clearly-articulated assumption?

**Comment by iancharest** [comment]
I know @lajnd has been looking into some fixes for indicator.py

**Comment by eberlot** [comment]
Because there's been more commits since this issue was raise, I've also just now pushed another commit fixing an issue with allpairs (@saarbuckle and I noticed it was previously returning only zeros). But I think it would be good to resolve and decide whether we want indicator.py util to be able to deal with column and row vectors before any further work is done on indicator.py.

**Comment by doerlbh** [comment]
Sounds good. Thanks for opening this issue. BTW, feel free to edit the test_indicator.py accordingly as well, and to meet the checks by codeclimate and travis (unittest). Thanks!

**Comment by HeikoSchuett** [comment]
As these functions are only taking vectors I would fix this by calling a single np.flatten() on the input once. Would that fix this issue?
