### ISSUE TITLE
How to perform permutation statistical test?

### ISSUE THREAD

**Issue by RylanSchaeffer** [rsagroup/rsatoolbox#249]
Hi! I'm reading the Kriegeskorte, Mur & Bandettini paper, and Step 5 recommends using a permutation test when comparing 2 RDMs. I can't find out how to perform this permutation test using the `rsatoolbox` package. Can you point me in the right direction?

> STEP 5: TESTING RELATEDNESS OF TWO DISSIMILARITY MATRICES BY RANDOMIZATION. We therefore suggest testing the relatedness of dissimilarity matrices by randomizing the condition labels. We choose a random permutation of the conditions, reorder rows and columns of one of the two dissimilarity matrices to be compared according to this permutation, and compute the correlation. Repeating this step many times (e.g., 10,000 times), we obtain a distribution of correlations simulating the null hypothesis that the two dissimilarity matrices are unrelated.

**Comment by JasperVanDenBosch** [comment]
hi @RylanSchaeffer, thanks for your question. Ideally you'd have RDMs for the underlying sample, e.g. an RDM for each participant. In this case have a look [here](https://rsatoolbox.readthedocs.io/en/latest/demo_bootstrap.html), and keep in mind that you could consider one of the RDMs to be a "model" for the other.

For the permutation approach you mentioned, it'd be a combination of [permute_rdms](https://github.com/rsagroup/rsatoolbox/blob/9301f39f0b6adda2c59f957ffe902ef28ecd905a/rsatoolbox/rdm/rdms.py#L513) and [compare](https://github.com/rsagroup/rsatoolbox/blob/308f9a7d6e2848c147234fa525fbc14f991c3672/rsatoolbox/rdm/compare.py#L19).

**Comment by RylanSchaeffer** [comment]
Do I need to combine the two functions myself? Or is there a way to pass some argument to compare saying I want to perform a permutation-based statistical test?

**Comment by RylanSchaeffer** [comment]
Also, how do researchers nowadays evaluate RSA approaches? Do they still use permutation tests?

**Comment by JasperVanDenBosch** [comment]
> Do I need to combine the two functions myself? Or is there a way to pass some argument to compare saying I want to perform a permutation-based statistical test?

I'll discuss with the other on whether we should build this, and get back to you asap

**Comment by RylanSchaeffer** [comment]
Thanks! I ask because when I compare two matrices, I want to know that (under whatever metric I select), the performed comparison uses the best statistical hypothesis test for whether the matrices are more likely independent or dependent.

**Comment by nkriegeskorte** [comment]
dear rylan,

the permutation test you mention is an excellent way to test for
relatedness against the null hypothesis that the two representations whose
RDMs you are comparing are unrelated. the test takes the dependency
structure of RDMs into account and requires only the minimal assumption of
exchangeability of the condition labels under the null hypothesis.

however, this is a very low bar, because different representations of the
same stimuli tend to share information and this usually is reflected in
some positive (though possibly low) RDM correlation. (the related notion of
"distance correlation" even formally provides an indicator of
mutual information between stimulus and response, which here would
corresponds to model features and brain responses or two sets of
model features or two sets of brain responses.)

note also that the condition-label randomization test treats subjects and
experimental conditions (e.g. stimuli) as fixed effects. so you are testing
for relatedness in your experimental subjects and conditions, without
addressing whether the variability across subjects and conditions suggests
that the correlation holds for the underlying populations of subjects and
experimental conditions.

if you set test_above_0=True in the model_plot arguments, you will see a
more generalizable test for positive correlation of the data RDM and the
model RDM (treating subjects and/or conditions as random effects as is now
standard).

moreover, theoretical progress requires that we compare representational
hypotheses. the question then is whether one model better explains the data
RDM than another model.

for all these reasons, the condition-label randomization test is not the
most informative and high-priority thing to look at and no longer part of
the standard model evaluation as visualized by the model plot function.

still it should be provided by the toolbox as an option as it can still
serve useful purposes, e.g. as a sanity check when RDMs are extremely
noisy, when you have too few subjects and stimuli to use bootstrapping, or
when you are only interested in your sample of subjects and your sample of
stimuli, rather than trying to test general hypotheses about their
populations.

niko




____________________________________________________
Nikolaus Kriegeskorte, PhD
Professor of Psychology and Neuroscience
Affiliated member, Department of Electrical Engineering
Director of Cognitive Imaging, Zuckerman Mind Brain Behavior Institute
Columbia University
***@***.***

**Comment by RylanSchaeffer** [comment]
Hi Professor Kriegeskorte,

Thanks for getting back to me! The use case I'm specifically interested in is asking which model's RDM best matches the data RDM (from a set of candidate models), or ideally, what is the rank of the models based on their RDM matches to the data RDM. What is the (sequence of) recommended analyses and best practices to answer this question?

Based on what you said above, it seems like a permutation test isn't necessarily the best approach, but what instead is?

**Comment by RylanSchaeffer** [comment]
I might be using terminology inconsistently with `rsatoolbox`. The documentation suggests that a `Model` predicts an RDM e.g., "The simplest type of model are fixed models, which simply predict a single RDM." By model, I mean some system that produces vector outputs for inputs that are then subsequently used to compute RDMs

**Comment by RylanSchaeffer** [comment]
To clarify my use case, I have $M$ candidate models and a set of $P$ stimuli $x_1, ..., x_P$, as well as neural recordings from one subject shown those stimuli. How can I rank the candidate models?

**Comment by nkriegeskorte** [comment]
that's exactly what the toolbox is for: inferential comparisons among
multiple models.

these two papers summarize our current wisdom on this:
https://nbdt.scholasticahq.com/article/27664-comparing-representational-geometries-using-whitened-unbiased-distance-matrix-similarity
https://arxiv.org/abs/2112.09200





____________________________________________________
Nikolaus Kriegeskorte, PhD
Professor of Psychology and Neuroscience
Affiliated member, Department of Electrical Engineering
Director of Cognitive Imaging, Zuckerman Mind Brain Behavior Institute
Columbia University
***@***.***

**Comment by RylanSchaeffer** [comment]
Yes, that's why I'm looking at this toolbox. The problem is that I can't
find a clear answer about what the best / recommended evaluation method is
in the documentation, so I'm asking for directions.

Cheers,
Rylan Schaeffer

**Comment by nkriegeskorte** [comment]
we're still working on the documentation and demo scripts.
perhaps this demo script is a good starting point:
https://github.com/rsagroup/rsatoolbox/blob/main/demos/demo_bootstrap.ipynb

heiko may have further pointers.



____________________________________________________
Nikolaus Kriegeskorte, PhD
Professor of Psychology and Neuroscience
Affiliated member, Department of Electrical Engineering
Director of Cognitive Imaging, Zuckerman Mind Brain Behavior Institute
Columbia University
***@***.***

**Comment by RylanSchaeffer** [comment]
Can one of you please clarify what a `rsatoolbox.inference.result.Result`'s `.evaluations` are?

The demo doesn't really say, and the documentation just says these are "evaluations." What is the actual evaluation or test or measurement being performed?

> evaluations (numpy.ndarray) – evaluations of the models over bootstrap/crossvalidation format: bootstrap_samples x models x crossval & others such that np.mean(evaluations[i,j]) is a valid evaluation for the jth model on the ith bootstrap-sample

**Comment by RylanSchaeffer** [comment]
Now I'm even more confused. Under the hood, `eval_fixed` just calls `compare(rdm_pred, data, method)` for each model. Where is model evaluation performed? Where is some notion of cross validation or generalization or a statistical test for significance/effect size computed?

**Comment by nkriegeskorte** [comment]
the model evaluations (e.g. using a correlation between data and model RDM)
are performed inside the bootstrap loop.
for a conceptual description of the inference, see heiko's paper linked
above.



____________________________________________________
Nikolaus Kriegeskorte, PhD
Professor of Psychology and Neuroscience
Affiliated member, Department of Electrical Engineering
Director of Cognitive Imaging, Zuckerman Mind Brain Behavior Institute
Columbia University
***@***.***

**Comment by RylanSchaeffer** [comment]
Oh this is great - thank you!

Cheers,
Rylan Schaeffer

**Comment by JasperVanDenBosch** [comment]
I'll close this as it seems @RylanSchaeffer 's question was resolved
