### ISSUE TITLE
`fit_regress_nn` returns array of `nan` when all weights are zero

### ISSUE THREAD

**Issue by psychNerdJae** [rsagroup/rsatoolbox#263]
Presently, `fit_regress_nn` returns the following:
`theta.flatten() / np.sqrt(np.sum(theta ** 2))`

If all weights in `theta` are exactly zero, this returns a vector of `nan` instead of zeroes, as theta is divided by zero.

**Comment by jdiedrichsen** [comment]
Yes- it is not clear to me why the regression weights would be standardized at all (here or in any other fitting function). This seems to be a pretty undesireable feature? @HeikoSchuett ? @ilogue

**Comment by HeikoSchuett** [comment]
Hi @psychNerdJae & @jdiedrichsen,
it certainly seems undesirable to return the NaNs here, this is true. I coded in the standardization, because (almost) all comparison methods yield the same evaluation for any scaling of the RDM, such that the solution space always contains a whole line not a single parameter value. To yield consistent results, I thought it was better to standardize the weights than to return the essentially random scaling created by the fitting function.

I will definitely include a check for zero to avoid the NaNs though.
