### ISSUE TITLE
Normalization of theta weights after model fitting

### ISSUE THREAD

**Issue by jdiedrichsen** [rsagroup/rsatoolbox#396]
Hi all - 
I think we have been over this before, but I wanted to question again why we normalize the regression weights to length 1 after fitting in rsa.model.fitter

This often renders results non-interpretable, especially if you want to know how much variance each model component is actually explaining. 

Example: 
Fitter - line 387. :     return theta.flatten() / np.sqrt(np.sum(theta ** 2))

I would argue we should make it default to return the original coefficients. If normalization is required for subsequent inference in some cases, then we can have an optional input parameter that allows you to get the normalized parameter (Or for transparency sake, normalize them in the calling routine). 

best, 

Joern

**Comment by HeikoSchuett** [comment]
Hi @jdiedrichsen,

Note that the norm of theta is largely uninterpretable for the linear models though. Almost all comparison metrics that we optimise are scale invariant, i.e. for the linear model any multiple of theta will be equally good. Thus, different Fitters can give you very different values if you do not normalise. Also, we often need to normalise the target RDMs to get equal weighting across the different RDMs. Thus, you will have to take normalisation into account either way if you want to have a sensible variance explained or similar metrics. 

I think the main positive effects of this normalisation are comparability between fitters and numerical stability as values do not get very large or small this way.

To me, it sounds like you actually want a different normalisation rather than no normalisation. 

Are you still convinced that you want the raw fit values? If so, I don't think it will break much if we move the normalisation to all places where we want to compare fitting results to each other. 

best
Heiko

**Comment by jdiedrichsen** [comment]
Hi Heiko, 
 
I disagree - the size of the regression coefficient directly relates to the prediction and to the explained variance within the RDM. While it is true to that most model comaprisions we use in the RSA toolbox are scale invariant, that is not true for using model families, where it is handy to derive the scaled predicted covariance matrix. I am happy to walk you through an example I had in mind. 

I think there should be at least an option to turn the normalization off and a note that the default is to have it on. 

Joern

**Comment by JasperVanDenBosch** [comment]
We've discussed this today and will make this a flag (well-documented) such that the normalization can be turned off

**Comment by HeikoSchuett** [comment]
This issue is resolved by #411
