### ISSUE TITLE
Matplotlib 3.9.1 wheels broken on windows

### ISSUE THREAD

**Issue by JasperVanDenBosch** [rsagroup/rsatoolbox#412]
See https://github.com/matplotlib/matplotlib/issues/28551

The wheels have been yanked from pypi which is why our windows builds are failing. I will try to blacklist this version of mpl.

For example error see [this run](https://github.com/rsagroup/rsatoolbox/actions/runs/10238021232/job/28322122730)

**Comment by JasperVanDenBosch** [comment]
Temporary fix in ae0a8b81813beebda96c1ad0dd6bf3116e141aa9. Does not fix source builds for older python versions; But I suspect this is due to the Github runners not having the required system packages anymore.

**Comment by tacaswell** [comment]
The 3.9.1 wheels on windows would, depending on import order, cause segfaults, see https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266699619.

We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel.  We have now yanked the whole 3.9.1 release to fix these problems and will get 3.9.2 out as quick as we can.

To prevent this sort of thing in the future (trying to build something from source when you are not prepared to do so) I suggest using `matplotlib --only-binary "matplotlib" ` in your requirements file (which may be a good practice for all wheels that have extensions).

Sorry for the trouble.

**Comment by JasperVanDenBosch** [comment]
Thanks @tacaswell , really appreciate your effort! MPL is very important to us.

 The `--only-binary` would make a lot of sense on CI for the packaging aspect of things, but I wonder if this would work for all end-users (i.e. do they always have access to wheels on their HPC?). Then we could have separate requirements of course, but the more they'd diverge, the more it would diminish the usefulness of the CI for catching issues users may face. I'll have to think about this a bit more and discuss with the team.

**Comment by tacaswell** [comment]
It is also possible to set the only-binary via on env https://pip.pypa.io/en/stable/topics/configuration/#environment-variables as `PIP_ONLY_BINARY=matplotlib` on CI and leave it out of the requirements file.  

I think it is also possible to do something like

```
matplotlib --only-binary "matplotlib"; sys_platform == 'windows'
matplotlib
```

as it is far more likely that a unix-like system will have a compiler available.

This is also only a problem with pip, if your end users are using any other packaging environment (I know some HPC systems have conda available (iirc NERSC even has locally tuned variants)) this is irrelevant.
